### ISSUE TITLE
encodeUnicode encodes Emojis in URLs

### ISSUE THREAD

**Issue by tldev-de** [elvanto/litemoji#39]
I'm using this library to encode emojis in HTML. We experience the problem, that emojis in links are encoded as well, which leads to faulty links.

This is a sample input:
```html
<h1>This is a heading :party:</h1>
<a href="https://dbsw.sharepoint.com/:x:/r/teams/Data/123">This is a link!</a>
```

This is the outcome:
```html
<h1>This is a heading 🎉</h1>
<a href="https://dbsw.sharepoint.com/❌/r/teams/Data/123">This is a link!</a>
```

This is the expected outcome:
```html
<h1>This is a heading 🎉</h1>
<a href="https://dbsw.sharepoint.com/:x:/r/teams/Data/123">This is a link!</a>
```

Is there any way to limit the conversion to shortcodes, which have a space before or after the shortcode? E.g. ` :x:`, `:x: `. This would prevent the conversion of "shortcodes" in links, which should not  include unescaped spaces!

Of course, I could parse the html and iterate through the filtered texts, which seems quite complex. Maybe there is a better / simpler solution for this problem?

At the moment I help myself by parsing the html and iterate through all links after the first conversion:

```php
$html = LitEmoji::encodeUnicode($html);
$dom = new Dom();
$dom->loadStr($html);
$dom->find('a')->each(function ($a) {
    $a->setAttribute('href', LitEmoji::unicodeToShortcode($a->getAttribute('href')));
});
$html = $dom;
```

Thanks for any help in advance! :)

**Comment by joshmcrae** [comment]
Hi Tobi, sorry for the delay in getting back to you.

Differentiating between portions of a text being converted (e.g. content and URLS, or tags and body within an XML document) is outside the scope of this library. I think your approach of parsing the HTML and dealing with the `href` attribute separately from the rest of the document is a good start. That said, it might be better to only `encodeUnicode()` on the portions of the document that are rendered rather than converting the whole document and then 'fixing' the links by converting them back.

Even a simple regex that splits the HTML on URLs might be enough for you to avoid this issue?
