### ISSUE TITLE
CLDR emoji shortcodes

### ISSUE THREAD

**Issue by loranger** [elvanto/litemoji#42]
Hello,

Could you please consider supporting CLDR emoji list?
I try to parse outline export but their shortcode are [CLDR](https://emojibase.dev/shortcodes/?filter=thumb) (flag_ instead flag-, thumbs_up instead thumbsup, etc…).

Is there a simple way to add an extra shortcode list ? Or maybe a way to add aliases to shortcodes, or include new custom codes?

By the way, thank you so much for this very useful lib 👍🏻

**Comment by joshmcrae** [comment]
Hi Laurent,

The shortcodes we currently use are from Emojibase. We use their datasets as a dev dependency to [generate a mapping](https://github.com/elvanto/litemoji/blob/master/bin/generate-shortcodes-array.php) that gets pulled in to the library the first time [LitEmoji::getShortcodes()](https://github.com/elvanto/litemoji/blob/master/src/LitEmoji.php#L208) is called.

The simplest approach I can think of to supporting standard shortcode presets is for us to maintain multiple mappings and allow you to configure LitEmoji to use a specific mapping by name, e.g. by calling `LitEmoji::useShortcodes('cldr')` before you do anything else with the library.

One potential downside is that shortcodes from different presets wouldn't work simultaneously - i.e. `:thumbsups:` **or** `:thumbs_up:` would work, but not both, depending on what preset you're using.

We're happy to accept pull requests if you're able to attempt these changes, otherwise let me know and I'll get something implemented when I have time.

**Comment by joshmcrae** [comment]
Closing as we've got solutions for this in [5.1.0](https://github.com/elvanto/litemoji/releases/tag/5.1.0).
